### ISSUE TITLE
Comments field not rendering

### ISSUE THREAD

**Issue by apawl** [allenta/gitlab-listener#14]
I just installed GitLab Listener and it connects fine but the content in the comments field is sort of mixed up. It's almost in need of markdown.

Anyone every experience this?

**Comment by carlosabalde** [comment]
I've never seen that. Could you share some more details: JIRA version, a screenshot showing this, the HTML markup, etc.

**Comment by apawl** [comment]
Thanks for responding - I really appreciate that!

Here is the output to JIRA for the comments section:

[saviles@XXXX.com|https://git.XXXXair.com/u/saviles] mentioned this issue in [a commit of XXXXit/test-jenkins|https://git.XXXXair.com/XXXXi
t/test-jenkins/commit/d74155be7e0c711926ec0c7c7dffd770cb3aa2d6].

**Comment by carlosabalde** [comment]
Are you sure you are using the [GitLab Listener add-on](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener)? It does no generate any string like "... mentioned this issue in...". That message was generated by something else.

**Comment by apawl** [comment]
I have the GitLab Listener 1.1.7 configured to a GitLab Enterprise with a webhook.

**Comment by carlosabalde** [comment]
I see, but comments generated by the GitLab Listener add-on look like `Changeset <commit id> pushed to GitLab <summary of the commit message>`. That's completely different from that comment you have pasted. That's generated by something else.

**Comment by apawl** [comment]
According to the developer its coming from https://git.XXXXair.com/ and pushed to JIRA which is 6.4.1

I am an admin on both

**Comment by apawl** [comment]
So the user is using a text editor to submit changes to GitLab Enterprise. Those comments look just fine in Git. Git is automatically sending off the messages to JIRA - I am guessing using a JIRA Service Template. Once in JIRA they are coming over with links.

**Comment by apawl** [comment]
![git-step1](https://cloud.githubusercontent.com/assets/8712655/9336525/aaa36260-459f-11e5-95ca-5bae71d3c2ef.png)
![git-step2](https://cloud.githubusercontent.com/assets/8712655/9336527/ae6498a6-459f-11e5-8fb9-230acfdc0ad5.png)
![git-step3](https://cloud.githubusercontent.com/assets/8712655/9336530/b4b0ad12-459f-11e5-8215-7f7d2c2fdaad.png)

**Comment by carlosabalde** [comment]
I get your problem, but as I said those comments are **not** being generated by the GitLab Listener add-on. Perhaps they are sent by the JIRA integration available in GitLab Enterprise, but definitely not by the add-on.
