### ISSUE TITLE
Commits being processed intermittently

### ISSUE THREAD

**Issue by briantist** [allenta/gitlab-listener#15]
I've been creating a number of new projects in gitlab recently. The files are already in local repos, and the existing commits use `#refs` tags. When I add the remote to the local repo and push, I'm not getting any comments on the referenced JIRA issues. In one case I was able to delete and recreate the project and it seemed to work, but the others still show no comments. 

I'm also seeing that it did not create comments for each commit, only 2 commits out of 4 were processed; the other 2 were ignored.

I know this is all rather vague, but I'm having a hard time figuring out where the issue is. I suspect it's in the plugin, because even when no commits show up, I am able to see through tcpdump that gitlab is indeed making a connection to JIRA. Also some of the commits are being turned into JIRA comments, so clearly the information is making it into there, it's just not being processed all the way.

The logs in gitlab don't seem to indicate anything, and all I can find in JIRA's logs (`atlassian-jira.log`) are 2 messages:

```
2015-09-08 15:10:20,435 http-bio-443-exec-162 WARN anonymous 910x640441x1 - x.x.x.x /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Commit has already been processed (see http://_hostname_/gitlab/bscholer/revere/commit/dc557ca2963a112fa243cf6c1b2c7d4a6dc7dabb).
2015-09-08 15:10:20,435 http-bio-443-exec-162 WARN anonymous 910x640441x1 - x.x.x.x /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Commit has already been processed (see http://_hostname_/gitlab/bscholer/revere/commit/870f7c7a69b702681d0a01de9f741edf0402c86b).
```

These are the 2 commits (of 4 total) that were successful, so I'm not sure why these messages show up, but other than those there are no messages from the plugin whatsoever.

Is there any way I can get detailed logs about what the plugin is receiving, how it's processing the data, etc.?

**Comment by carlosabalde** [comment]
If I understood this correctly, you're facing two different problems.

On the one hand, when creating a new project in GitLab, and after setting up the web hook in the project settings in order to submit all push events to the listener add-on running in JIRA, you change the remote of an existing repository and push all commits to GitLab. In this  case you don't get anything logged in JIRA.

I assume you have checked the logs of JIRA while doing some of those pushes and you didn't find any error message related with the add-on (I'm sorry, but there is not any detailed log; the add-on only generated log records on error / warning situations). If that's the case, I would say that GitLab is not sending the push notifications. Have you checked this using tcpdump? Did you configured the web hook properly?

On the other hand, in some cases some commits do not show up in JIRA and you get those "... Commit has already been processed..." messages in JIRA's log. Those are warning messages generated by the add-on. The add-on keeps track of past commits identifiers already processed. If a commit with the same identifier is submitted more than once, that commit is ignored and a warning message logged. At the moment (and this is a limitation of the current implementation of the add-on) if more than one commit with the same identifier is submitted, even if those commits belong to different GitLab projects, only the first one is going to be processed. Could you check if you are experiencing that problem?

**Comment by briantist** [comment]
Hi @carlosabalde , sort of correct. I realize don't have a good consistent picture of the problem yet which is why I was looking for better logging. In the case of creating a new project, it has both worked, and not worked.

I have checked with tcpdump on the gitlab side and it does appear to be sending the notifications. I did configure the webhook properly (it had been working on other projects for a while, it's the same URL).

> On the other hand, in some cases some commits do not show up in JIRA and you get those "... Commit has already been processed..." messages in JIRA's log.

This is not quite correct. Only 2 of those messages showed up in the log, and the commits referenced were ones that **did** show up in the comments in JIRA. That push actually contained 4 commits, but the commits that were missing were not referenced in the jira logs.

In another case, a new repo I created had a similar problem. The push contained ~20 commits, but only 2 showed up in the comments (this time, no messages in the jira logs at all).

It seems very unlikely to me that I would suddenly have so many commits that are duplicates (and if that were the problem I would expect more warning messages in the jira logs but there aren't any).

Where is the cache of commits? If I can look at the cache, I can rule this out quickly by looking for any commit that no comment was generated for.

Thanks!

**Comment by carlosabalde** [comment]
Hi @briantist. Thanks for your feedback. I've just released a new version of the add-on (1.1.8) including some extra logging logic. Some rare error conditions are now logged. Additionally, if you enable DEBUG level, you'll get more information from the add-on in the JIRA log (e.g. when a push notification is received, etc.). Hopefully this will help to understand what's going on here.

**Comment by carlosabalde** [comment]
On the other hand, the cache of commits is stored in the JIRA database. If you look for tables containing the word `commit` in their names you should be able to find it easily. It's a simple one-column table containing the list of already processed commits.

**Comment by briantist** [comment]
@carlosabalde thanks for the info and the new release. Which log in particular do I need to set to the `DEBUG` level?

**Comment by briantist** [comment]
The cache table (2 columns, `HASH` and `ID`) only has 15 rows, so it can't think that it has processed all of the commits since one of my repos has 20. I'll get the new release and see what I can see.

**Comment by briantist** [comment]
Ok, so far here's what I've been able to tell with the new version. The issue of only 2 commits showing up is because those came in via the `Test Hook` button in GitLab. Apparently the way that's implemented is to take the 2 most recent commits and submit them. Seems strange to me that they'd use live data for such a test, but it does explain why that button gives me a 500 error when the project is empty.

I wrote a quick web app that I added as an additional web hook, then removed a project and recreated it. I added both the plugin and my app as hooks, then pushed (this is the one with 20 commits).

There are no messages in the JIRA log (I still can't figure out where to enable `DEBUG` logging, enabling it on `com.atlassian.jira` seems to have no effect).

My web app recorded this info (redacted) from that initial push:

```
{
    "before": "0000000000000000000000000000000000000000",
    "after": "cfef7b0d1778a5da53bbae38852ac801881842a5",
    "ref": "refs/heads/master",
    "user_id": 11,
    "user_name": "briantist",
    "repository": {
            "name": "repo",
            "url": "git@vcs.domain:briantist/repo.git",
            "description": "Desc",
            "homepage": "http://vcs.domain/gitlab/briantist/repo"
    },
    "commits": [],
    "total_commits_count": 0
}
```

So it makes sense that the plugin doesn't post any comments, when it's not being informed of any commits!

I realize that this is probably now outside the scope of this project, but do you know if this behavior is expected in GitLab? Is it a bug? Am I doing something wrong? Thanks for your help.

**Comment by briantist** [comment]
Ok, it looks like this is known/expected behavior, as annoying as that is. It looks like this is what will happen if I started my repo locally and later decided to push it to gitlab, meaning I won't get any of my messages in JIRA :(

https://gitlab.com/gitlab-org/gitlab-ce/issues/490
https://github.com/gitlabhq/gitlabhq/issues/8401

Thank you again for your help, I would still like to know for future reference which log to set to `DEBUG` to get the extended info.

**Comment by briantist** [comment]
Workaround, for anyone else who might have this issue:
1. Removed project
2. Recreated project
3. Add web hook
4. Create a blank repo somewhere locally
5. Add remote
6. Create and commit some dummy file
7. Push to remote
8. On the "real" local repo, Pull to get the dummy file
9. Remove dummy file and commit
10. Push to remote from there
11. Remove dummy repo

I was able to get all the comments in that way, and because the plugin remembers existing commit IDs, the 2 that were previously successful were not duplicated.

**Comment by carlosabalde** [comment]
Hi @briantist. Just for further reference, the steps to enable `DEBUG` level are:
1. Log in as an user with the 'JIRA System Administrators' global permission.
2. Choose 'System'. Then select 'Troubleshooting and Support > Logging & Profiling' to open the Logging page.
3. Scroll to the 'Default Loggers' section and click 'Configure logging level for another package'.
4. Package name is `com.allenta.jira.plugins.gitlab.listener.Servlet`.

Thanks for your help and for the workaround!
