### ISSUE TITLE
Show GIT activity under separate tab

### ISSUE THREAD

**Issue by krohnecode** [allenta/gitlab-listener#16]
While I appreciate the "Use activities instead of comments" option, this still leaves GIT commits mixed in with a lot of other actions.

Can we get an option to show this under a separate tab, like the DVCS Connector plugin does for GitHub and Bitbucket?

**Comment by carlosabalde** [comment]
Hi @krohnecode. Thanks for the suggestion. I'm not sure if that's going to be added in future releases but we'll discuss it internally.

**Comment by cweiske** [comment]
I got that working for my gitorious integration with jira; see https://github.com/netresearch/klonfisch#screenshots - you have to provide a web application implementing the stash API, though.

**Comment by cweiske** [comment]
did you implement it?

**Comment by carlosabalde** [comment]
I was timing out the issue. I'm sorry but finally this is not going to be implemented. Thanks for your understanding.
