### ISSUE TITLE
Failed to process the incoming request: invalid payload.

### ISSUE THREAD

**Issue by thomseno** [allenta/gitlab-listener#20]
JIRA 6.4.10, GitLab Listener 1.21 (payed licence), GitLab 5.4.2

With latest update Gitlab Listener stopped working with our "old" GitLab 5.4.2... was working previously... TRACE level log does not give any more information:

```
2015-10-01 10:14:22,638 http-bio-8180-exec-10 DEBUG anonymous 614x112074x1 - 127.0.0.1 /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Ready to process a new incoming request.
2015-10-01 10:14:22,642 http-bio-8180-exec-10 ERROR anonymous 614x112074x1 - 127.0.0.1 /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Failed to process the incoming request: invalid payload.
```

**Comment by carlosabalde** [comment]
GitLab Listener 1.2.0 and later of the add-on need to have access to the GitLab project ID in the GitLab web hook notifications. GitLab 5.4.2 is probably not including that piece of information.

**Comment by thomseno** [comment]
Ok... downgraded to version 1.1.8... now it's working again. Looked in the documentation of GitLab 5.4.2 and you're right: there is no "project_id" :frowning: Is it possible to handle the "project_id" optional?

**Comment by carlosabalde** [comment]
I can think about some possible workarounds to make `project_id` optional, but they are all really ugly. Additionally, I think that the `project_id` field is available in web hook notifications since GitLab 6.0. Let me think about possible alternatives and I'll get back to you asap.

**Comment by thomseno** [comment]
Cool... thanks!

**Comment by carlosabalde** [comment]
A new version (1.2.2 for JIRA < 7.0; 2.0.2 for JIRA >= 7.0) of the add-on including the workaround to support legacy GitLab instances has just been released. Since GitLab is not going to include the `project_id` field in the web hook notifications, alternatively you can provide it manually in the web hook URLs. It must be an integer (ideally the identifier of the GitLab project) value and you should use different values for each GitLab project. When present in the web hook URL the one in the JSON payload will be ignored. Example:

```
https://example.com/jira/plugins/servlet/gitlab/listener?secret=s3cr3t&instance=legacy&project=42
```

Note that the `instance` parameter is only recommended if you have multiple GitLab instances submitting notifications to JIRA.

Hope this helps.

**Comment by thomseno** [comment]
Works like a charm... thanks again :+1:

**Comment by carlosabalde** [comment]
You're welcome! :dancer:

**Comment by ghost** [comment]
Hi! I could not manage this.

I tried to add '&instance=legacy&project=42', '&project=42' and '&project_id=42' to my webhook url but I still get the error

2015-10-22 14:49:42,542 http-bio-8181-exec-11 ERROR anonymous 889x23406x1 - 192.168.105.107 /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Failed to process the incoming request: invalid payload.

BTW I see 'target_project_id' in Gitlab notification... Is it wrong one?

**Comment by carlosabalde** [comment]
Hi @ulrith! Could you share here a JSON notification submitted by your legacy GitLab instance?

**Comment by ghost** [comment]
Yes. Actually I try to hook listener from my own code with the following request:

POST / HTTP/1.1
Host: 127.0.0.1:8765
Content-Type: application/json
X-Gitlab-Event: Merge Hook
Accept: application/json
Content-Length: 1849
Expect: 100-continue

**Comment by carlosabalde** [comment]
It looks like that's a "merge request" event. The add-on only understands "push events". Are you sure you have set up the web hook type correctly?

**Comment by ghost** [comment]
Hm, I need to invoke the listener on Merge event... Are there a way to send to the listener some fake request which include minimal necessary data and message with commands for Jira? What do you advice?

**Comment by carlosabalde** [comment]
You can try, but the add-on is explicitly designed to only process push events. Anyway, when you generate a merge commit, that commit will be pushed and it will be notified by the push web hook.

**Comment by ghost** [comment]
I want to trigger "Open', 'Close' and 'Merge' actions in Gitlab itself to my Jira instance. I think that first two of them do not generate push event...

**Comment by carlosabalde** [comment]
I think I get what you want to do, but the add-on does not provide support for those web hook notifications. I'm sorry.

**Comment by ghost** [comment]
Thank you for your help, I've implemented this as direct call to Jira API.
