### ISSUE TITLE
Option to restrict visibility of changes in JIRA?

### ISSUE THREAD

**Issue by shwaffles** [allenta/gitlab-listener#21]
Not too picky about how this is implemented, but mostly I know there will be people who don't like gitlab info being visible to all users with issue access, and it's way too much to go back and edit the comment visibility later.

The two ways I can think of would be to let us configure a default visibility restriction when Listener is set to post comments (e.g., visible only to 'Developer' role), and to make it look like developer tool activity when Listener is set to post to the activity feed, since tool activity can be restricted in permission schemes.

The first one seems like the easiest one to implement. The second one might not even be possible, but it's all I could think of.

**Comment by carlosabalde** [comment]
Hi @josidhe. Thanks for the suggestion. It looks like a nice feature to include in the add-on. I'll look into this asap (probably not this week) and I'll get back to you with some conclusions and ideas.

**Comment by carlosabalde** [comment]
I've been looking at this and it seems a reasonable and easy to implement feature. The attached screenshot shows how the new settings page will look like. As you can see, new options to restrict visibility of comments and worklogs generated by the add-on to a specific project role will be available. Hopefully this will be released during next week.

![screenshot](https://cloud.githubusercontent.com/assets/342614/10762681/4cea0a66-7cc7-11e5-8702-301f6d23da8f.png)

**Comment by shwaffles** [comment]
Nice! And thanks! I'm glad to hear it wasn't impossible to do. This will make me feel a lot more confident pushing this add-on to teams at my company.

**Comment by carlosabalde** [comment]
This feature is now available in GitLab Listener [1.2.3](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100200300) (JIRA 6.x) and [2.0.3](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000300) (JIRA 7.x).

Sorry for the delay. Something came up and I was not able to complete this earlier. Thanks!
