### ISSUE TITLE
Option to change issue key format

### ISSUE THREAD

**Issue by Qronicle** [allenta/gitlab-listener#22]
Our company is using a slightly different issue key format than the default JIRA format. 
(We use 3 alphas followed by 3 numerics to identify client and project, for example: CLI005-123)

I'm guessing you're using a regular expression to parse the commit messages, so maybe it could become an option the change this expression?

**Comment by carlosabalde** [comment]
I'm not sure adding a configurable regexp to the configuration of the add-on is the best option here. I guess you changed the issue key format using the procedure described [here](https://confluence.atlassian.com/jira/changing-the-project-key-format-192534.html), right? If so, the configurable parameter already exists and it's just a matter of using it in the add-on.

**Comment by Qronicle** [comment]
I asked our JIRA administrator, and we have indeed changed the jira.projectkey.pattern parameter.
We're using the value `([A-Z0-9-]{2,10})`

So using this parameter seems like the better option,  yes :)

**Comment by carlosabalde** [comment]
This feature is now available in GitLab Listener [1.2.4](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100200400) (JIRA 6.x) and [2.0.4](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000400) (JIRA 7.x). Thanks!

**Comment by Qronicle** [comment]
Thanks a lot!

**Comment by carlosabalde** [comment]
You're welcome. And don't forget to share with your colleagues, family and friends how better is life using the GitLab Listener add-on! :smile_cat:
