### ISSUE TITLE
Support commit format <ISSUE-1>: <description of the commit>

### ISSUE THREAD

**Issue by bwaldvogel** [allenta/gitlab-listener#26]
Would it be possible to additionally support a colon (`:`) after the issue key?

Example:
- `ISSUE-1: some description`

**Comment by carlosabalde** [comment]
Yes, it will be added in the next release. Thanks for the suggestion!

**Comment by carlosabalde** [comment]
This feature is now available in GitLab Listener [1.2.5](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100200500) (JIRA 6.x) and [2.0.5](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000500) (JIRA 7.x). Thanks!

**Comment by bwaldvogel** [comment]
It works, thanks!
