### ISSUE TITLE
Linked as committs in JIRA??

### ISSUE THREAD

**Issue by davebown** [allenta/gitlab-listener#27]
Does integration from gitlab link as commits and branches with the ability to browse the changes in them in JIRA like with github and bitbucket or are does it just create comments?

**Comment by carlosabalde** [comment]
The add-on allows generating comments (or activities) referencing changesets pushed to GitLab, but it does not allow to view diffs, browse branches, create tags, etc. inside JIRA. The philosophy is using **the right tool for each job**; no JIRA add-on could ever beat GitLab for those tasks. The point of the add-on is allowing an easy way to jump from JIRA to GitLab. Additionally, the add-on allows generating JIRA worklogs, execute workflow transitions, etc. using some directives included in commit messages. No more, no less.
