### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by krispii** [allenta/gitlab-listener#29]
Once the plugin updates complete, they indicate looking at release notes. There doesn't seem to be an obvious place where they might be waiting for us.

More importantly, can we see them beforehand?

Thanks!

**Comment by carlosabalde** [comment]
That depends on JIRA, not on the add-on. Anyway, you can always check out the release in https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions.

**Comment by krispii** [comment]
I do think it might help to have them here - where the documentation points - just an idea from a customer. ;) Thanks again.

**Comment by carlosabalde** [comment]
Thanks. I'll do that in future releases! :+1:
