### ISSUE TITLE
Logging time does not automatically adjust remaining estimate

### ISSUE THREAD

**Issue by AKoetsier** [allenta/gitlab-listener#3]
When logging time in a commit message the remaining time will stay the same instead of subtracting it (as is the default in Jira).

**Comment by carlosabalde** [comment]
Hi,

I've just tested this creating a new issue, setting a estimate of `6h` and then pushing a couple of commits to GitLab (one logging `10m` and one logging `50m`), and it seems to be working.

![time](https://cloud.githubusercontent.com/assets/342614/6594742/2ec2b47c-c7e4-11e4-8033-faa8eba2dbeb.png)

Are you able to see the logged work in the 'Work Log' tab?

**Comment by AKoetsier** [comment]
What you show here is exactly the same result as we get. However what I mean is that it doesn't subtract the logged time from the remaining time (the jira default). In the screenshot you can see that the remaining time is still 6h although you spend 1h on it already. 

You can see the estimated now has an extra light bar that indicates that the time spend + time remaining is more than the estimated time.

If you stick to the jira default it should update the remaining time by subtracting the logged time from it.

**Comment by carlosabalde** [comment]
Got it! We've just [released 1.1.3](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100100300) fixing this. Please, let us know is the fix works for you. Thanks!

**Comment by AKoetsier** [comment]
You guys rock! It works now. Thanks for the quick response and fix!
