### ISSUE TITLE
Fallback user should not get added to watchers list

### ISSUE THREAD

**Issue by infernix** [allenta/gitlab-listener#32]
I've created a JIRA user called `gitlab` as a fallback user when email addresses do not match users in jira. However, if this is the case, the `gitlab` JIRA user comments on the issue and then gets added to the watchers list. This will then lead to notifications being sent to said user.

Since this is a system user, we don't need it to be on the watchers list at all. Would be great to either disable this entirely or make this an option.

**Comment by carlosabalde** [comment]
I think this kind of feature (i.e. disable e-mails notifications per user) should be something provided by JIRA.

**Comment by infernix** [comment]
But JIRA does not provide it (dozens of reports over the years if you google it so that situation is hopeless), and the fallback user functionality is in your addon so somehow this automatically places this user on the watchlist.

I'm not asking to not send notifications, I'm asking to prevent the fallback user to get on the watchlist.
