### ISSUE TITLE
Customisable commit message format

### ISSUE THREAD

**Issue by pduersteler** [allenta/gitlab-listener#34]
The currently supported message formats do not match our specs, and prefixing it with any hashtag clutters the message. I'd like to see an option where it does not matter where the commit message key is.

Not sure if the option "Look for issue keys globally" would do this or not, as it is not explained anywhere.

**Comment by carlosabalde** [comment]
1. If you're using reasonable commit messages (i.e. subject including short description followed by details in the body), you can include the `#refs` directive in the body part (e.g. in the last line). I don't think that would clutter the message.
2. When enabling the 'Look for issue keys globally' option, issue keys will be searched in the whole commit message (i.e. not only at the beginning of the message or inside the message prefixed by the `#refs` directive.
