### ISSUE TITLE
Workflow action flexibility

### ISSUE THREAD

**Issue by shwaffles** [allenta/gitlab-listener#37]
There are a lot of strong feelings about workflows and transition names sometimes, so I was thinking it'd be nice if there was a way to create common names for workflow actions that can be used for all workflows while still letting people name things what they want in the JIRA UI.

All I could think of was properties. It might not even be realistic to ask for, or there might be a much simpler approach, but could gitlab listener designate a property ID that transitions could use? For example, a "code review" status could have many different transition names in a dozen different JIRA projects, but I could edit those workflows and give all of the "Request Code Review" transitions a key/value property like:

gitlab.listener.action = review

And then commit notes could contain "#action review" and trigger the matching transition.

Is that crazy?

**Comment by carlosabalde** [comment]
Hi @josidhe. Thanks for the suggestion. I think it makes sense and I see a bunch of different approaches to implement the behaviour you're looking for, however I'm not sure this would be useful for most users. I'm already receiving too many reviews of the add-on complaining about the obscurity behind some configuration options. I'd prefer to keep it simple unless more users are really interested in this feature.

**Comment by shwaffles** [comment]
No worries. But be optimistic -- that...particularly negative review on the marketplace has 0 people "find this helpful", so at least that's nice. :P Never had more than one headache with this add-on, and that was just learning that it couldn't see commits in "pushed new branch" actions (gotta push branch, THEN push commit). Other than that? Pffff. Easy mode.
