### ISSUE TITLE
Allocating time with #time does not interpret decimal fractions for hours

### ISSUE THREAD

**Issue by fallasd** [allenta/gitlab-listener#38]
Hello,
I recently installed your GitLab Listener v1.2.8 add-on with an evaluation license on our in-house JIRA instance (Windows Server 2008). I have been using the #time feature to add JIRA Work Log descriptions and allocating time.

I have found that whilst whole numbers for hours and minutes work correctly, using decimal fractions for hours - for example '2.5h' - does not. Allocating time in Work Log directly into the JIRA Issue Work Log field correctly records '2 hours, 30 minutes'.

Should the add-on be able to interpret decimal fractions for hours correctly?

I also note that attempting to transition a new open issue to In Progress fails. The commit comment is as follows:
DL-4 - #action in progress Create tracking issue and start investigations #time 2.5h

**Comment by carlosabalde** [comment]
I confirm the add-on currently does not support decimal values when using the `#time` directive. A new version fixing that is ready. Unfortunately I've not been able to upload it yet to the Atlassian Marketplace. It seems uploads of new versions of add-ons to the marketplace are currently broken. I'll keep trying and I'll post here again as soon as the new version is available.

**Comment by carlosabalde** [comment]
Bug should now be fixed in GitLab Listener [1.2.9](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100200900) (JIRA 6.x) and [2.0.9](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000900) (JIRA 7.x). Thanks for reporting!
