### ISSUE TITLE
Possible to "replay" old commits?

### ISSUE THREAD

**Issue by toreau** [allenta/gitlab-listener#4]
It would be really nice if it was possible to somehow replay/import old commits into JIRA. Is that possible?

**Comment by carlosabalde** [comment]
This is a simple add-on completely relaying on notifications submitted from GitLab to JIRA. Being able to import commits from JIRA on demand is not trivial. However, creating a script to loop through commits in a git repository and submitting "fake" GitLab webhook notifications to JIRA should be pretty simple :)

**Comment by bwaldvogel** [comment]
I’ve actually implemented a python script to manually post "lost" commits (#24) to the web hook. However, I’ve noticed that the commit timestamps are not honored and the current time seems to be used. Is this a known issue?

**Comment by carlosabalde** [comment]
Initial versions of the add-on used timestamps in the commit messages to generate comments, worklogs, etc. This behaviour seemed a little bit weird and it was changed by the current behaviour (use the timestamp associated with the webhook notification).

**Comment by bwaldvogel** [comment]
So is there a workaround or would it be possible to make the behavior configurable?
Otherwise replaying old commits is effectively not possible.

**Comment by carlosabalde** [comment]
Please, append `&replay=1` to the webhook URL you're using in your replay script. The workaround is now available in GitLab Listener [1.2.5](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b100200500) (JIRA 6.x) and [2.0.5](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000500) (JIRA 7.x). Thanks!

**Comment by bwaldvogel** [comment]
Wow, thanks!
It works for me.

**Comment by eliskovets** [comment]
@bwaldvogel Could you please share your script? It looks like it's still not implemented in gitlab-listener plugin and I'm sure the script would be very useful for people who is migrating to gitlab.
Thanks.

**Comment by bwaldvogel** [comment]
@eliskovets: see https://github.com/cronn-de/jira-gitlab-listener-replay
