### ISSUE TITLE
Resolution in commit message has no effect

### ISSUE THREAD

**Issue by sunew** [allenta/gitlab-listener#42]
Commit message:

GFDEMO-3 #action done, duplicate

The workflow transition is done. The resolution 'duplicate'.

The resolution in jira becomes 'done' (the default resultion).

And in the actions it looks strange: 
![selection_110](https://cloud.githubusercontent.com/assets/893142/17746023/86509dfe-64ae-11e6-88b6-cd1644bf882d.png)

The correct resultion, 'duplicate', shows in the Original Value column, but the new value becomes done.

The previous resultion was not 'duplicate', but unresolved.

We have set up a screen in jira when marking issues as done, where you are forced to choose a resolution. Maybe this can be the cause of the issue?

**Comment by sunew** [comment]
Also, same pattern when we are transitioning issues from "under review" with the transition called 'accept' to the state Done, and a resolution (could be 'done', 'duplicate', 'won't fix' etc.).

GFDEMO-3 #action accept, duplicate

**Comment by carlosabalde** [comment]
I've been unsuccessfully trying to reproduce the issue in a fresh JIRA 7.0.0 installation using the 'project management' workflow and a couple of different resolutions (`duplicate` and `won't do`), but everything is working as expected. In particular the logged actions look as expected.

To be honest I don't know if this could be related with the screen you mentioned or with some other special configuration in your environment. What JIRA version are you using?

**Comment by sunew** [comment]
We are using JIRA Software 7.1.7.

I'll try to reproduce with a standard project, not using the 'Resolve Issue Screen'.

**Comment by sunew** [comment]
I can reproduce with jira software 7.1.7

Create a default scrum project. This project by default gets the Software Simplified Workflow. This workflow has a post function on the Done transition, setting the resolution to 'done'.

The resolution from this commit message:

```
Test TSTPL-1 #action done, Duplicate
```

has no effect.

![selection_111](https://cloud.githubusercontent.com/assets/893142/17785588/aaa3b406-6581-11e6-9220-8d8f481557d9.png)

![selection_112](https://cloud.githubusercontent.com/assets/893142/17785615/c4308462-6581-11e6-8aae-11ed59c4ef59.png)

**Comment by carlosabalde** [comment]
This time I used a fresh JIRA 7.1.7 installation and I created a Scrum project using the Software Simplified Workflow. Workflow transitions are working as expected. Resolutions are not working but I think this is the expected behaviour too because you are not allowed to set a custom resolution when making a transition in this workflow (i.e. specific resolutions are associated to each state).  This is consistent with the UI because I can't see a way to set a resolution when executing a transition. So, still not sure if this is or not a bug, but what the add-on does is consistent with what can be done in the UI.

**Comment by sunew** [comment]
Fine. In my case I have to decide how to configure the workflow. One possibility is to remove the post function, making it possible to set resolution from a commit message.

A combination of using the buildt-in 'Resolve Issue Screen', and removing the post function, would make it possible to set a resolution from the UI or from a commit message.

But one problem: if people via commit message transition an issue to state Done, without setting a resolution, the issue would not get a resolution. And as noted here, https://confluence.atlassian.com/adminjiraserver071/working-with-workflows-802592661.html
under "Setting the resolution field":

> "In JIRA, an issue is either open or closes, based on the value of its 'Resolution' field — not its 'Status' field.
> An issue is open if its resolution field has not been set.
> An issue is closed if its resolution field has a value (e.g. Fixed, Cannot Reproduce).
> This is true regardless of the current value of the issue's status field (Open, In Progress, etc). Therefore, if you need your workflow to force an issue to be open or closed, you will need to set the issue's resolution field during a transition. There are two ways to do this:
> Set the resolution field automatically via a post function.
> Prompt the user to choose a resolution via a screen. See Working in text mode for details on this."

In line with this, you would need to either force a Done transition via commit message to set a resolution, or to have a default resolution set if the commit message has no resolution. Usually done via post functions, but apparently the post function triggers after the actions taken by the gitlab-listener plugin.

Possible to fix this via adding a setting for a default resolution for the plugin?

Also, this would be good input for the documentation:)

And thanks for the good work with the plugin.
