### ISSUE TITLE
Include short commit hash in Jira Comment

### ISSUE THREAD

**Issue by pbi-qfs** [allenta/gitlab-listener#46]
Most times it is sufficient to use the first, say, 8 characters of a commit hash to identify it. It would be great if we could configure GitLab Listener in a way that the displayed hash length in the comment is shorter.

**Comment by carlosabalde** [comment]
Added your suggestion to the list of ideas to be explored. Thanks!

**Comment by carlosabalde** [comment]
This has been [added in version 2.0.11](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000920).
