### ISSUE TITLE
Cannot get the listener to trigger the transition in JIRA

### ISSUE THREAD

**Issue by Cindy-Brown** [allenta/gitlab-listener#47]
Downloaded and set up gitlab-listener Add-On. When the developer does the push the following from GitLab to JIRA as follows:

irvingr pushed to branch development of PAR/wintak (Compare changes)
ed41551c: WTK-1434 New commo binaries #action resolves issue

A comment is added to issue "WTK-1434", but the ACTION is not triggered.
The log file shows the following:

2016-11-16 16:00:39,433 http-bio-8443-exec-52 ERROR irvingr 960x60124x1 - xx.xxx.xx.xxx,0:0:0:0:0:0:0:1 /plugins/servlet/gitlab/listener [c.a.j.p.gitlab.listener.Servlet] Failed to execute JIRA workflow action: a matching action was not found (https://git.url/PAR/wintak/commit/ed41551ca6345f46a095feda06382a718177eca6). 

Have you had others run across this issue? If so, any clue as to why the commit is not triggering the transition to "Resolved"?

**Comment by carlosabalde** [comment]
Yes, I've seen this in the past (e.g. https://github.com/allenta/gitlab-listener/issues/33). Using an invalid action name in the `#action` directive is the usual reason. You need to check the workflow associated to the project and use the name shown in one of the edges.

**Comment by Cindy-Brown** [comment]
Is the action name Case Sensitive?

**Comment by carlosabalde** [comment]
No, it's case insensitive.

**Comment by Cindy-Brown** [comment]
I am assuming that when you say – “use the name shown in one of the edges” you are referring to the JIRA Workflow “Transition” name, correct?

We also set up the push trigger in GitLab to match the “Transition” “Code_Resolve”, would that be correct?

I have attached 2 screenshots for clarity.

Thanks,

Cindy

**Comment by carlosabalde** [comment]
Screenshots are missing.

**Comment by Cindy-Brown** [comment]
So sorry. There were attachments. Maybe they got stripped out.

I will try again with a zipped file.

Cindy

**Comment by carlosabalde** [comment]
You should try using the web UI.

**Comment by Cindy-Brown** [comment]
I am not sure what you mean by that.

Cindy

**Comment by carlosabalde** [comment]
I mean opening https://github.com/allenta/gitlab-listener/issues/47 in a browser, login in GitHub and write the comment (and attach the screenshots) using the web interface (i.e. not using your e-mail client).

**Comment by Cindy-Brown** [comment]
![jira_workflow](https://cloud.githubusercontent.com/assets/23509790/20401773/2f9c2afc-acc8-11e6-8359-66a1828b6d3a.PNG)

**Comment by Cindy-Brown** [comment]
![gitlab_trigger](https://cloud.githubusercontent.com/assets/23509790/20401778/349d6fc0-acc8-11e6-959e-279633c68980.PNG)

**Comment by Cindy-Brown** [comment]
![gitlab-listener-shared-secret](https://cloud.githubusercontent.com/assets/23509790/20401995/f1ed273c-acc8-11e6-8283-f82a1010eed7.PNG)

**Comment by carlosabalde** [comment]
Thanks for the screenshots! 

The value of the `#action` directive in the commit message was `resolves issue`, however, as you can see in the column 'Transitions' shown in the first screenshot, that name doesn't match any valid transition. Perhaps you wanted to use a commit message like `WTK-1434 New commo binaries #action resolve`?

The second screenshot in not related with the GitLab Listener add-on. The third one shows an empty configuration  of the add-on.

**Comment by Cindy-Brown** [comment]
Here is another example that did not trigger the transition:

60478377: Check for null on the import manager view

WTK-1517 #action Code_Resolve

**Comment by carlosabalde** [comment]
That's not very useful if you don't include what's dumped to the log file. Also, beware that you need a valid transition name, but also a task in the right state to execute that transition.

**Comment by Cindy-Brown** [comment]
We did end up getting it to work. The developers used the correct action name just now and the transition was triggered successfully. Thank you for your help.

**Comment by carlosabalde** [comment]
You're welcome! Thank your for using the add-on.
