### ISSUE TITLE
Enable Systemhook

### ISSUE THREAD

**Issue by alwinmark** [allenta/gitlab-listener#49]
The only USP for me to buy that plugin would be the enabling of the Systemhook.

Currently with the built-in Integration of Gitlab I have to define a JIRA Project and everything for every Project so I have to with your plugin.

If I could define a system hook and your plugin could handle that, It would be a real usability boost worth paying for it.

Currently when I try doing sth like that, I can see in Logs that the push was received but the Listener couldn't identify any commit.

**Comment by alwinmark** [comment]
OK as far as I can see, this is not a problem of your Plugin but a gitlab Problem.

**Comment by carlosabalde** [comment]
Glad to hear that. Sorry for the silence in the line but it have been busy days for me. Thanks!

**Comment by alwinmark** [comment]
Hi,

so after talking to gitlab https://gitlab.com/gitlab-org/gitlab-ce/issues/25117#note_20389840 I'm pretty sure you have to fix it in the Plugin as this behavior is intended by gitlab. So basically the Plugin has to look between the `before` and `after` hash and not the commit list for Systemhooks. I guess it's nothing trivial :cry:

**Comment by carlosabalde** [comment]
Hi @alwinmark,

I've checked the thread you referenced and now I see the problem. As you know the add-on depends on push webhook notifications (i.e. https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md#push-events). I agree it would be nice being able to define a global push webhook event, but as you've found a push system hook event (i.e. https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/system_hooks/system_hooks.md#push-events) sadly does not work as someone would expect. 

Using the `before` and `after` pointers would do the job, but that would require bidirectional GitLab ⟷ JIRA communication, which would break the way the add-on works (only GitLab ➝ JIRA communication).
