### ISSUE TITLE
multiple jira projects per single git repository possible?

### ISSUE THREAD

**Issue by snormann** [allenta/gitlab-listener#51]
We're using GitLab Community Edition 8.11.4.  Gitlab jira integration seems to require that only a single jira project can be referenced per repository.  Our team uses multiple projects to track issues against our repository - something like 6-10 jira projects for changes to the same code base.

Is it possible to configure gitlab-listener so that comments can refer to different jira project issues for commits made to the same repository?

**Comment by carlosabalde** [comment]
Yes, GitLab Listener allows referencing more than one issue in a single commit message. Referenced issues may belong to a single or to multiples JIRA projects.
