### ISSUE TITLE
Skipping commit: it does not reference any JIRA issue

### ISSUE THREAD

**Issue by asfaltboy** [allenta/gitlab-listener#52]
This is displayed in the DEBUG log, however, the commit quoted does indeed reference an existing issue. This happens with some of the projects, but not all of them.

Was on Jira 6.4.14 and gitlab-listener 1.2.9 , upgraded to Jira 7.3 and latest gitlab-listener 2.0.9

**Comment by carlosabalde** [comment]
Please, share some commit descriptions generating that message. That message is generated when parsing the commit message and no issues matching the project key format are found.

**Comment by btaub** [comment]
We ran into this problem too. Enabling the "Look for issue keys globally" checkbox in the Add-on settings fixed it for us.

![image](https://cloud.githubusercontent.com/assets/1743650/25723522/53c8f8ea-30e6-11e7-85a4-f3ade39beff8.png)

**Comment by asfaltboy** [comment]
I never knew about this option, any chance this can be documented: what it does, and in which cases do users need to activate it?

We have since moved to another method of syncing gitlab data, so if this resolved the exact issue, feel free to close it

**Comment by carlosabalde** [comment]
Not sure if this solves the exact issue because a failing commit message example was never provided, but I guess it could be related because the default behaviour is looking for issue keys only at the beginning of the commit description (not in the whole commit message).

**Comment by btaub** [comment]
Here's an obfuscated example from our env:

`2017-05-04 14:39:43,013 http-bio-443-exec-23 DEBUG anonymous 879x367462x1 - x.x.x.x /plugins/servlet/gitlab/listener [plugins.gitlab.listener.Servlet] Skipping commit: it does not reference any JIRA issue (https://x.x.x.x/engineering/<project>/commit/03174929xxxxxxxxxxxxxxx).
`

commit msg for 03174929:
`testing - XX-1494
`

XX-1494 was a valid, open JIRA ticket.

**Comment by carlosabalde** [comment]
When enabling the 'Look for issue keys globally' option that commit message is processed as expected, right?

**Comment by btaub** [comment]
Yes, it's working now with that option enabled. From the example commit messages listed here https://github.com/allenta/gitlab-listener#commit-messages - I thought it would have worked by default, but it was inconsistent. It worked for some people and not for others. Now it works for everyone.

**Comment by carlosabalde** [comment]
Great! I agree documentation could be improved. We'll see what I can do. Thanks!
