### ISSUE TITLE
Possible to choose action/transition based on branch?

### ISSUE THREAD

**Issue by TobbenTM** [allenta/gitlab-listener#54]
Hi!

Quick question; with this plugin, is it possible to automatically select the action/transition in jira based on what branch it has been comitted to? 

We're doing a git workflow where whenever we commit to certain branches, we would like the Jira issues in the merges to be transitioned to the correct state. If not possible today, is this something you could see implemented in the future?

**Comment by carlosabalde** [comment]
Hi @TobbenTM,

It's not possible today and I don't think that's going to be implemented in the future.
