### ISSUE TITLE
Question on GitLab Community Edition 8.14.3 Integration

### ISSUE THREAD

**Issue by ScopiCisco** [allenta/gitlab-listener#55]
Hello Team,

We are attempting to integrate GitLab Community Edition 8.14.3 with JIRA v6.3.9#6339-sha1:46fa261 using gitlab-listener addon 1.2.9.  Currently the email address is not being used from gitlab.  I was wondering if you could identify which field the listener is looking for?

Thanks,
Scott Saltsgaver

**Comment by carlosabalde** [comment]
Hi,

The add-on looks for web-hook notifications sent by GitLab and extracts the e-mail address associated to the commit. Example:

```
{
  "project_id": ...,
  "commits": [
    {
      "id": "...",
      "message": "...",
      "timestamp": "...",
      "url": "...",
      "author": {
        "name": "Carlos Abalde",
        "email": "cabalde@allenta.com"
      }
    },
    ...
```

I'd recommend enabling debug messages as described in https://github.com/allenta/gitlab-listener#how-to-enable-debug-level, push some commits to GitLab and then check what's going on in the JIRA side.

**Comment by ScopiCisco** [comment]
Hello Carlos,

Thank you for the quick response.  One more question, does LDAP integration in JIRA affect the lookup?  

I have verified that my author.email matches what JIRA shows me in the UI.  

Thanks,
Scott

**Comment by ScopiCisco** [comment]
Hello Carlos,

We figured it out.  It was a user to ADD_COMMENT permission issue.

Thanks,
Scott

**Comment by carlosabalde** [comment]
Thanks!
