### ISSUE TITLE
Incorrect url in documentation

### ISSUE THREAD

**Issue by karoljoc** [allenta/gitlab-listener#56]
Good day,

I was struggling for hours trying to figure out why my integration is not working and luckily stumbled on an old issue where they mentioned the url they are using. Your documentation states that the url is 

{{{
https://www.example.com/jira/plugins/servlet/gitlab/listener?secret=t0ps3cr3t&instance=default
}}}

It's suppose to be

{{{
https://www.example.com/plugins/servlet/gitlab/listener?secret=t0ps3cr3t&instance=default
}}}

**Comment by carlosabalde** [comment]
The specific URL prefix depends on your JIRA installation. ``/jira/`` is a common one, but (1) it's not mandatory; and (2) a different one could be used.

**Comment by karoljoc** [comment]
It would help if you mentioned that in the documentation
