### ISSUE TITLE
Security issue: X-Gitlab-Token HTTP header

### ISSUE THREAD

**Issue by droberin** [allenta/gitlab-listener#57]
This plugin would be much more secure if we could use X-Gitlab-Token HTTP header for authentication.
Gitlab already provides a field for webhooks called "Secret Token" which will use its value in that header field.

Is there any restriction inside JAVA/Jira that forbids the plugin to receive this header?

If we could use this feature, there woudn't be any clear-password shown in every project webhook list. This password provides an easy method to attack JIRA service by a "DDoS attack" leaving a dirty database full of comments. Please, tell me if I'm wrong about this matter.

Thanks, folks.

**Comment by carlosabalde** [comment]
You're right. The only reason to use the secret token included in the webhook URL instead of the ``X-Gitlab-Token`` header is that header didn't exist when the add-on was created. Adding this should be trivial. Thanks!

**Comment by droberin** [comment]
It would definitely be great since Gitlab users with developer role in projects can see webhooks but can't see tokens from the current webhooks in it.
Hope to see this feature added in coming release(s)!

Thanks for the quick answer.

**Comment by carlosabalde** [comment]
This has been [added in version 2.0.11](https://marketplace.atlassian.com/plugins/com.allenta.jira.plugins.gitlab.gitlab-listener/versions#b200000920).
