### ISSUE TITLE
How to enforce Jira issue number in commits? 

### ISSUE THREAD

**Issue by monstrfolk** [allenta/gitlab-listener#58]
Please explain the following. I would like to set this up. How do I?

You may enforce inclusion of JIRA issues in all commit messages defining a simple git hook in the local copies of the repositories.

**Comment by carlosabalde** [comment]
You need to create a server-side hook enforcing inclusion of a JIRA issue ID in all commit messages. [This StackOverflow answer](https://stackoverflow.com/a/37718213/1806102) is a good starting point.
