### ISSUE TITLE
Does this plugin supports multi commits in single push events?

### ISSUE THREAD

**Issue by dingxiaobo** [allenta/gitlab-listener#61]
I configured webhook on gitlab with 'push events'.

try like this: 

one commit with jira issue id, then push. jira issue page related my commit in remark view.

one commit without jira issue id, one commit with jira issue id, then push. jira doesn't detect my commit.

I checked my webhook history, request has been send, but the plugin seems not recognize this request.

![image](https://user-images.githubusercontent.com/23743074/46928507-72c00680-d06d-11e8-9039-1852faf706a1.png)

**Comment by carlosabalde** [comment]
Yes, the add-on supports receiving multiple commits in single push events. When a new push notification reaches the add-on, the JSON payload is parsed and then the `project_id` (integer) and `commits` (array) fields are extracted. Then every commit in the array in processed.

If you think you can reproduce the problem, I'd suggest enabling the add-on debug level, forcing some GitLab push notifications, and then check messages in the JIRA log.

**Comment by dingxiaobo** [comment]
> Yes, the add-on supports receiving multiple commits in single push events. When a new push notification reaches the add-on, the JSON payload is parsed and then the `project_id` (integer) and `commits` (array) fields are extracted. Then every commit in the array in processed.
> 
> If you think you can reproduce the problem, I'd suggest enabling the add-on debug level, forcing some GitLab push notifications, and then check messages in the JIRA log.

Problem resolved. Thanks a lot.
