### ISSUE TITLE
Add support for merge request events

### ISSUE THREAD

**Issue by thomasbergmann** [allenta/gitlab-listener#64]
Merge request events are currently not supported as mentioned in #59.

Please add support. In my experience teams transitioning issues based on opened and merged MRs.

**Comment by fmuelhaupt** [comment]
Is there an ETA on this feature? Why even let Users select events, which are not supported?

**Comment by carlosabalde** [comment]
> Is there an ETA on this feature?

No ETA. We might consider this in the future, but at the moment it's just in the backlog.

> Why even let users select events, which are not supported?

Events are selected in the GitLab UI. The add-on has not any control on that UI.

**Comment by hvhaugwitz** [comment]
Is there any update on this feature request?

**Comment by carlosabalde** [comment]
I confirm this is finally not happening. Sorry!

**Comment by hvhaugwitz** [comment]
What are the reasons?

It would be quite useful to create a merge request and automatically link it in the referenced ticket.

**Comment by carlosabalde** [comment]
Yes, completely agree it's a nice thing to have. The decision is about priorities, resources, etc.
