### ISSUE TITLE
Duplicate comment for the same commit

### ISSUE THREAD

**Issue by andersharrisson-ess** [allenta/gitlab-listener#66]
Hi,
When pushing the same commit to a separate repo (such as a fork) a duplicate comment will be added. Is this by design or should this be addressed?

I noticed the old issue https://github.com/allenta/gitlab-listener/issues/7 that addresses the duplicate comments for commits on multiple branches. Is there a way to ignore duplicates from different repos as well?

**Comment by carlosabalde** [comment]
Hi @andersharrisson-ess,

What you see is the expected behaviour. Identical commits (i.e. same hash) are ignored by GitLab project.
