### ISSUE TITLE
Implementing Webhook into Gitlab does not work

### ISSUE THREAD

**Issue by dtamm** [allenta/gitlab-listener#68]
Hi there,

we just have the plugin in its test period and set up the webhook URL in our gitlab projects, which should be connected to our JIRA. As we entered our JIRA URL (e.g.: https://jira.company.com/plugins/servlet/gitlab/listener?secret=t0ps3cr3t&instance=default) including the Token in the Gitlab Project and made our first commit, nothing in the used JIRA Issue happend (no comment and no worklog from the message was parsed). We tried both ways:

- Using the Github Windows Client
- Using Windows Command Line Tool

Neither of these ways works! Within our tests we used a simple Commit Message as the following: "TP-6 Changed Readme #time 1h"

We also tried to analyse the log files of JIRA but did not see anything in there. Also, we had a look into the webhook details (request and response) and did not see anything suspicious (though the response of the called URL was empty, but the request did return an 200 status code from the server).

Out setup:

JIRA Server > Version 8.3.3 (Docker Image by Teamatldocker: teamatldocker/jira:latest)
Gitlab CE > Version 12.2.4 (Docker Image by Gitlab: gitlab/gitlab-ce:latest)

Both on the same machine, run under different subdomains.

I hope the stated information are enough for first impression and maybe you can help!

Regards,
Dominik

**Comment by carlosabalde** [comment]
Please, enable the add-on debug level, push some commits, and then check messages in the JIRA log. Hopefully that should help you to understand the problem.

**Comment by dtamm** [comment]
Thanks, that really helped us out. We so identified the problem: the issue expression is f**** up, which is a general problem in our jira instance. So i will be setting up a new db and reimport the whole stuff asap, then it should be running smoothly (tested on a local jira + plugin trial with gitlab locally).
