### ISSUE TITLE
Error: Failed to process the incoming request: invalid payload.

### ISSUE THREAD

**Issue by absolut777** [allenta/gitlab-listener#69]
Hello,

Gitlab Listener worked fine with our Jira, but suddenly stopped working with error messages in logs: 

2019-10-25 11:54:38,241 http-nio-8080-exec-10 DEBUG anonymous 714x3663440x1 - 172.20.0.2,127.0.0.1 /plugins/servlet/gitlab/listener [c.a.j.p.gitlab.listener.Servlet] Ready to process a new incoming request.
2019-10-25 11:54:38,245 http-nio-8080-exec-10 ERROR anonymous 714x3663440x1 - 172.20.0.2,127.0.0.1 /plugins/servlet/gitlab/listener [c.a.j.p.gitlab.listener.Servlet] Failed to process the incoming request: invalid payload.

GitLab: gitlab-ce-12.4.0-ce
Jira: 7.12.1
GitLab Listener: 2.0.11 (trial license)

**Comment by carlosabalde** [comment]
The `invalid payload` message is logged when the incoming GitLab JSON notification does not include a `project_id` field or a `commits` field. Any recent changes in the GitLab side?

**Comment by carlosabalde** [comment]
My recommendation: temporarily adjust the port of the notification URL in the GitLab side for some project, use something like `nc -l <port>` in the Jira side to capture the JSON payload submitted by GitLab, and then share it here. That would help to troubleshot this.

**Comment by absolut777** [comment]
`POST /plugins/servlet/gitlab/listener?secret=t0ps3cr3&instance=default HTTP/1.1
Content-Type: application/json
X-Gitlab-Event: Merge Request Hook
Connection: close
Host: j.cti.ru
Content-Length: 4311

{"object_kind":"merge_request","event_type":"merge_request","user":{"name":"Alexander Tkachev","username":"a.tkachev","avatar_url":"https://gitlab/uploads/-/system/user/avatar/57/avatar.png"},"project":{"id":480,"name":"cti-omni-doc","description":"........................  ...... .................. .... .................... c  CTI OMNI","web_url":"https://gitlab/portals-dev/cti-omni-doc","avatar_url":"https://gitlab/uploads/-/system/project/avatar/480/logo_3x.png","git_ssh_url":"git@gitlab:portals-dev/cti-omni-doc.git","git_http_url":"https://gitlab/portals-dev/cti-omni-doc.git","namespace":"portals-dev","visibility_level":0,"path_with_namespace":"portals-dev/cti-omni-doc","default_branch":"master","ci_config_path":null,"homepage":"https://gitlab/portals-dev/cti-omni-doc","url":"git@gitlab:portals-dev/cti-omni-doc.git","ssh_url":"git@gitlab:portals-dev/cti-omni-doc.git","http_url":"https://gitlab/portals-dev/cti-omni-doc.git"},"object_attributes":{"assignee_id":57,"author_id":57,"created_at":"2019-10-24 08:34:12 UTC","description":"","head_pipeline_id":null,"id":13182,"iid":22,"last_edited_at":null,"last_edited_by_id":null,"merge_commit_sha":null,"merge_error":null,"merge_params":{"force_remove_source_branch":"0"},"merge_status":"unchecked","merge_user_id":null,"merge_when_pipeline_succeeds":false,"milestone_id":null,"source_branch":"at-devops-51-test-zzz","source_project_id":480,"state":"opened","target_branch":"master","target_project_id":480,"time_estimate":0,"title":"[DEVOPS-51] At devops 51 test zzz","updated_at":"2019-10-24 16:27:23 UTC","updated_by_id":null,"url":"https://gitlab/portals-dev/cti-omni-doc/merge_requests/22","source":{"id":480,"name":"cti-omni-doc","description":"........................  ...... .................. .... .................... c  CTI OMNI","web_url":"https://gitlab/portals-dev/cti-omni-doc","avatar_url":"https://gitlab/uploads/-/system/project/avatar/480/logo_3x.png","git_ssh_url":"git@gitlab:portals-dev/cti-omni-doc.git","git_http_url":"https://gitlab/portals-dev/cti-omni-doc.git","namespace":"portals-dev","visibility_level":0,"path_with_namespace":"portals-dev/cti-omni-doc","default_branch":"master","ci_config_path":null,"homepage":"https://gitlab/portals-dev/cti-omni-doc","url":"git@gitlab:portals-dev/cti-omni-doc.git","ssh_url":"git@gitlab:portals-dev/cti-omni-doc.git","http_url":"https://gitlab/portals-dev/cti-omni-doc.git"},"target":{"id":480,"name":"cti-omni-doc","description":"........................  ...... .................. .... .................... c  CTI OMNI","web_url":"https://gitlab/portals-dev/cti-omni-doc","avatar_url":"https://gitlab/uploads/-/system/project/avatar/480/logo_3x.png","git_ssh_url":"git@gitlab:portals-dev/cti-omni-doc.git","git_http_url":"https://gitlab/portals-dev/cti-omni-doc.git","namespace":"portals-dev","visibility_level":0,"path_with_namespace":"portals-dev/cti-omni-doc","default_branch":"master","ci_config_path":null,"homepage":"https://gitlab/portals-dev/cti-omni-doc","url":"git@gitlab:portals-dev/cti-omni-doc.git","ssh_url":"git@gitlab:portals-dev/cti-omni-doc.git","http_url":"https://gitlab/portals-dev/cti-omni-doc.git"},"last_commit":{"id":"30227bc96207c117185fe27018b38251cfa5d0da","message":"[DEVOPS-51] Test0013\n","timestamp":"2019-10-24T16:27:01Z","url":"https://gitlab/portals-dev/cti-omni-doc/commit/30227bc96207c117185fe27018b38251cfa5d0da","author":{"name":"Alexander Tkachev","email":"a.tkachev@cti.ru"}},"work_in_progress":false,"total_time_spent":0,"human_total_time_spent":null,"human_time_estimate":null,"assignee_ids":[57],"action":"update","oldrev":"a3605423dd56e087417d7cc92b7d43ecd5f8881a"},"labels":[],"changes":{"total_time_spent":{"previous":null,"current":0}},"repository":{"name":"cti-omni-doc","url":"git@gitlab:portals-dev/cti-omni-doc.git","description":"........................  ...... .................. .... .................... c  CTI OMNI","homepage":"https://gitlab/portals-dev/cti-omni-doc"},"assignees":[{"name":"Alexander Tkachev","username":"a.tkachev","avatar_url":"https://gitlab/uploads/-/system/user/avatar/57/avatar.png"}]}

HTTP/1.1 200 
Server: nginx/1.15.6
Date: Thu, 24 Oct 2019 16:27:23 GMT
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
X-AREQUESTID: 1167x3632191x1
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
X-ASEN: SEN-L14337592
Set-Cookie: atlassian.xsrf.token=BT72-YXWF-JFHQ-G63D_fe77e04389b40b01883c4c1e04c234691b2d3921_lout; Path=/; Secure
X-AUSERNAME: anonymous

0`

**Comment by carlosabalde** [comment]
Let's format that JSON a little bit. As you can see, that's not a GitLab [push event](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#push-events) (which are the only events supported by GitLab Listener). It looks like you have configured the wrong trigger in the GitLiab side. Is it possible?

```
{
    "assignees": [
        {
            "avatar_url": "https://gitlab/uploads/-/system/user/avatar/57/avatar.png",
            "name": "Alexander Tkachev",
            "username": "a.tkachev"
        }
    ],
    "changes": {
        "total_time_spent": {
            "current": 0,
            "previous": null
        }
    },
    "event_type": "merge_request",
    "labels": [],
    "object_attributes": {
        "action": "update",
        "assignee_id": 57,
        "assignee_ids": [
            57
        ],
        "author_id": 57,
        "created_at": "2019-10-24 08:34:12 UTC",
        "description": "",
        "head_pipeline_id": null,
        "human_time_estimate": null,
        "human_total_time_spent": null,
        "id": 13182,
        "iid": 22,
        "last_commit": {
            "author": {
                "email": "a.tkachev@cti.ru",
                "name": "Alexander Tkachev"
            },
            "id": "30227bc96207c117185fe27018b38251cfa5d0da",
            "message": "[DEVOPS-51] Test0013\n",
            "timestamp": "2019-10-24T16:27:01Z",
            "url": "https://gitlab/portals-dev/cti-omni-doc/commit/30227bc96207c117185fe27018b38251cfa5d0da"
        },
        "last_edited_at": null,
        "last_edited_by_id": null,
        "merge_commit_sha": null,
        "merge_error": null,
        "merge_params": {
            "force_remove_source_branch": "0"
        },
        "merge_status": "unchecked",
        "merge_user_id": null,
        "merge_when_pipeline_succeeds": false,
        "milestone_id": null,
        "oldrev": "a3605423dd56e087417d7cc92b7d43ecd5f8881a",
        "source": {
            "avatar_url": "https://gitlab/uploads/-/system/project/avatar/480/logo_3x.png",
            "ci_config_path": null,
            "default_branch": "master",
            "description": "........................ ...... .................. .... .................... c CTI OMNI",
            "git_http_url": "https://gitlab/portals-dev/cti-omni-doc.git",
            "git_ssh_url": "git@gitlab:portals-dev/cti-omni-doc.git",
            "homepage": "https://gitlab/portals-dev/cti-omni-doc",
            "http_url": "https://gitlab/portals-dev/cti-omni-doc.git",
            "id": 480,
            "name": "cti-omni-doc",
            "namespace": "portals-dev",
            "path_with_namespace": "portals-dev/cti-omni-doc",
            "ssh_url": "git@gitlab:portals-dev/cti-omni-doc.git",
            "url": "git@gitlab:portals-dev/cti-omni-doc.git",
            "visibility_level": 0,
            "web_url": "https://gitlab/portals-dev/cti-omni-doc"
        },
        "source_branch": "at-devops-51-test-zzz",
        "source_project_id": 480,
        "state": "opened",
        "target": {
            "avatar_url": "https://gitlab/uploads/-/system/project/avatar/480/logo_3x.png",
            "ci_config_path": null,
            "default_branch": "master",
            "description": "........................ ...... .................. .... .................... c CTI OMNI",
            "git_http_url": "https://gitlab/portals-dev/cti-omni-doc.git",
            "git_ssh_url": "git@gitlab:portals-dev/cti-omni-doc.git",
            "homepage": "https://gitlab/portals-dev/cti-omni-doc",
            "http_url": "https://gitlab/portals-dev/cti-omni-doc.git",
            "id": 480,
            "name": "cti-omni-doc",
            "namespace": "portals-dev",
            "path_with_namespace": "portals-dev/cti-omni-doc",
            "ssh_url": "git@gitlab:portals-dev/cti-omni-doc.git",
            "url": "git@gitlab:portals-dev/cti-omni-doc.git",
            "visibility_level": 0,
            "web_url": "https://gitlab/portals-dev/cti-omni-doc"
        },
        "target_branch": "master",
        "target_project_id": 480,
        "time_estimate": 0,
        "title": "[DEVOPS-51] At devops 51 test zzz",
        "total_time_spent": 0,
        "updated_at": "2019-10-24 16:27:23 UTC",
        "updated_by_id": null,
        "url": "https://gitlab/portals-dev/cti-omni-doc/merge_requests/22",
        "work_in_progress": false
    },
    "object_kind": "merge_request",
    "project": {
        "avatar_url": "https://gitlab/uploads/-/system/project/avatar/480/logo_3x.png",
        "ci_config_path": null,
        "default_branch": "master",
        "description": "........................ ...... .................. .... .................... c CTI OMNI",
        "git_http_url": "https://gitlab/portals-dev/cti-omni-doc.git",
        "git_ssh_url": "git@gitlab:portals-dev/cti-omni-doc.git",
        "homepage": "https://gitlab/portals-dev/cti-omni-doc",
        "http_url": "https://gitlab/portals-dev/cti-omni-doc.git",
        "id": 480,
        "name": "cti-omni-doc",
        "namespace": "portals-dev",
        "path_with_namespace": "portals-dev/cti-omni-doc",
        "ssh_url": "git@gitlab:portals-dev/cti-omni-doc.git",
        "url": "git@gitlab:portals-dev/cti-omni-doc.git",
        "visibility_level": 0,
        "web_url": "https://gitlab/portals-dev/cti-omni-doc"
    },
    "repository": {
        "description": "........................ ...... .................. .... .................... c CTI OMNI",
        "homepage": "https://gitlab/portals-dev/cti-omni-doc",
        "name": "cti-omni-doc",
        "url": "git@gitlab:portals-dev/cti-omni-doc.git"
    },
    "user": {
        "avatar_url": "https://gitlab/uploads/-/system/user/avatar/57/avatar.png",
        "name": "Alexander Tkachev",
        "username": "a.tkachev"
    }
}
```

**Comment by absolut777** [comment]
Indeed. Trigger was set on "Merge request" event. I switch it to push event and the error was disappear. Thank you! But I still cannot see notification in our Jira tasks. Earlier we get notification like on this picture: https://yadi.sk/i/rkr4QTLzo-yXSg  Currently we are testing multiple Git Plugins in Jira and there is little mess:( Could you take a look to this picture and confirm that this notification was produced by GitLab Listener plugin?

**Comment by carlosabalde** [comment]
99,99% sure that notification was not produced by GitLab Listener.

**Comment by absolut777** [comment]
Actually I've found source of my problem. It was native integration Jira and Gitlab. Thank you for help!
