### ISSUE TITLE
#action does not activate transition

### ISSUE THREAD

**Issue by Mazorius** [allenta/gitlab-listener#70]
# Environment

GitLab v12.9.2
Jira v8.6.1

User has transition permission and can manually do the transition.

## Workflow Action

<img width="200" alt="Screen Shot 2020-04-15 at 15 53 40" src="https://user-images.githubusercontent.com/11423826/79345353-4bcbe480-7f31-11ea-9d8a-135cc71d0350.png">

## Commit Message

```
RPC-313: Add more information to README #action review ticket

RPC-313: improve project structure #action 'review ticket' 

RPC-313: Add more information to README #action Review Ticket

RPC-313: Add more information to README #action 71

RPC-313: Add more information to README #action review_ticket
```

## Jira Log

```
2020-04-15 15:00:02,868+0200 http-nio-8080-exec-4 ERROR ron.gebauer@company.com 900x52651414x1 - 217.111.43.58,127.0.0.1 /plugins/servlet/gitlab/listener [c.a.j.p.gitlab.listener.Servlet] Failed to execute JIRA workflow action: a matching action was not found (http://git.company.com/path/-/commit/<hash>).
```

---

Nothing of the above works. Did you have an idea why?

**Comment by carlosabalde** [comment]
First time I see something like this. Sadly there is not enough debug information to track this down a little bit. This it's just a wild guest, but could be please try with a commit message like `... #action in review` (i.e. using the name of the status instead of the name of the transition).

**Comment by Mazorius** [comment]
Unfortunately - this does not work either.

```
RPC-313: Change to exact one empty line at EOF #action in review
```

The activity was successful applied to the ticket.

**Comment by carlosabalde** [comment]
Is this a standard workflow I could try internally? If so, which one?

**Comment by Mazorius** [comment]
The workflow used was created especially for the project.

**Comment by carlosabalde** [comment]
So I guess best option here is releasing a new version of the add-on including additional debug information (basically, the names of the actions internally used to match the action included in the commit message). Hopefully at least that'll help to understand what's going on.

**Comment by Mazorius** [comment]
That would be great.

**Comment by carlosabalde** [comment]
No promises, but I'll try my best to have that new version ready during this week. I'll update this when available.

**Comment by carlosabalde** [comment]
[2.0.12](https://marketplace.atlassian.com/apps/1212989/gitlab-listener/version-history#b200000930) is available. It includes additional debugging messages that hopefully will help to understand what's going on. Please, look for `Checking JIRA workflow action...` debug messages when pushing a commit including an action. Hope it helps!

**Comment by Mazorius** [comment]
Thanks a lot!
I updated the plugin and activate debug output again.

I got the following message which seems to be the problem:
```
Checking JIRA workflow action 'review ticket' matches 'review ticket

    signed-off-by: ron gebauer <ron.gebauer@company.com>' in issue 'RPC-313' (http://git.company.com/path/-/commit/<hash>).
```

it seems that the signed-off-by statement which will be added at the end of a commit automatically by git with `-s` is not ignored by the check.

**Comment by carlosabalde** [comment]
Yes, that's for sure the problem. At the moment `#action` needs to be located at the end of the commit message.

**Comment by Mazorius** [comment]
This is a pity as it is an automatism of Git.

What would be the desired solution here?
* Cutting off the signed-off-by snippet before the test?
* Or separating the actions in `[]`? -> #action [review ticket, done] (If multiple action makes sense at all.)

**Comment by carlosabalde** [comment]
I think the ideal solution would be supporting quotes, brackets... to enclose values associated to directives like `#action`, `#time `, etc.

**Comment by carlosabalde** [comment]
[2.0.13](https://marketplace.atlassian.com/apps/1212989/gitlab-listener/version-history#b200000940) is available. It includes support for single quotes in `#refs`, `#time` and `#action` directives. Now you can use commit messages like `... blah blah #action 'review ticket, done' blah blah ...`. Please, let me know if that works for you.

**Comment by Mazorius** [comment]
That was quick :-)

With simple quotation marks it works now.

Thanks a lot for the support!

**Comment by carlosabalde** [comment]
You're welcome. Thank your for the helpful report & feedback! :)

**Comment by jovolp** [comment]
> [2.0.13](https://marketplace.atlassian.com/apps/1212989/gitlab-listener/version-history#b200000940) is available. It includes support for single quotes in `#refs`, `#time` and `#action` directives. Now you can use commit messages like `... blah blah #action 'review ticket, done' blah blah ...`. Please, let me know if that works for you.

@carlosabalde It would be helpful if an example of a multi-word transition was given in the README so that others don't have to sift through closed issues or the version history on Atlassian to know about this handy feature.
