### ISSUE TITLE
GitLab Listener stopped working due to deprecated method "getResolutionObjects()"

### ISSUE THREAD

**Issue by b1gBus** [allenta/gitlab-listener#72]
Hey there!

Thanks a lot for the great GitLab Listener add-on for Jira. It became crucial to our workflows.

**Actual result:**
Unfortunately with the latest update of our Jira Server instance (to version 9.0.0) the add-on stopped working for us and it seems that we identified an error:

`2022-08-02 11:37:05,429+0200 http-nio-8090-exec-20 url: /internal-error ERROR   -   [c.a.j.web.servlet.InternalServerErrorServlet] {errorId=e5e35ad6-95e7-481b-a4fc-1743bbdc40ad, interpretedMsg=, cause=java.lang.NoSuchMethodError: 'java.util.Collection com.atlassian.jira.config.ConstantsManager.getResolutionObjects()', stacktrace=java.lang.NoSuchMethodError: 'java.util.Collection com.atlassian.jira.config.ConstantsManager.getResolutionObjects()'`

The method getResolutionObjects() seems to be deprecated since Jira v.7.0 and seems to be removed with version v9.0 as it doesn't appear in the documentation anymore.

**Expected result:**
It would be wonderful if you could fix the error and use a non deprecated way of accessing the Resolution objects and provide a fixed version.

**External links:**
Jira v7.2. documentation: https://docs.atlassian.com/software/jira/docs/api/7.2.0/com/atlassian/jira/config/ConstantsManager.html
Jira v9.0. documentation: https://docs.atlassian.com/software/jira/docs/api/9.0.0/com/atlassian/jira/config/ConstantsManager.html

Thanks a lot it would be a pleasure to continue working with your great add-on.

Best regards,
Patrick

**Comment by th-lange** [comment]
Same issue here!

**Comment by carlosabalde** [comment]
I'm sorry, but we've decided that the add-on will no longer be supported post version 8.x and it will not be ported to Jira Data Center or Jira Cloud. We apologize for any inconvenience this may cause!
