### ISSUE TITLE
How to clear production data?

### ISSUE THREAD

**Issue by lukaszZmuda** [allenta/gitlab-listener#73]
Hello, 

We are going to migrate Jira production instance to non-production environments (UAT, DEV and so on).
What we have to remove in order to remove all sensitive data, but keep plugin configuration?

Regards,
Łukasz Żmuda

**Comment by carlosabalde** [comment]
If you want to keep the configuration, the only other information (not sure if I'd call that sensitive data) would be in the [DB table keeping track of the processed commits](https://github.com/allenta/gitlab-listener#performance).

**Comment by lukaszZmuda** [comment]
This one **AO_9B0D9B_PROCESSED_COMMIT**. Thank you very much!
